### ISSUE TITLE
Auto-Restart on Game Success

### ISSUE THREAD

**Issue by kgarner1** [henhouse/YeLinelubbers#8]
Title says it all.

**Comment by gbearley** [comment]
What is left for us to do on this project? Are we still going to try to make different difficulties?

Also, she mentioned that we had some sort of team review or something. Should we do that in person together or what?

**Comment by henhouse** [comment]
Any changes that you guys wanna make is fine, but I don't believe we have anything outstanding that must be done.

Yes, there is a group assignment due on Monday. That leaves no time to actually meet as a group and work on this. It looks like we're answering several questions, and not writing a one-page paper like we are doing for the retrospective, so I assume it's safe to just answer them and submit.

If you guys would like me to, I am fine with doing it. Also FYI the game is now live at: http://henhouse.github.io/YeLinelubbers/
